export const items = [
    { symbol: "A", type: "text", system: "Alphabet", label: "A", tags: ["letter", "SLP", "OT"] },
    { symbol: "B", type: "text", system: "Alphabet", label: "B", tags: ["letter", "SLP", "OT"] },
    { symbol: "C", type: "text", system: "Alphabet", label: "C", tags: ["letter", "SLP", "OT"] },
    { symbol: "D", type: "text", system: "Alphabet", label: "D", tags: ["letter", "SLP", "OT"] },
    { symbol: "E", type: "text", system: "Alphabet", label: "E", tags: ["letter", "SLP", "OT"] },
    { symbol: "F", type: "text", system: "Alphabet", label: "F", tags: ["letter", "SLP", "OT"] },
    { symbol: "G", type: "text", system: "Alphabet", label: "G", tags: ["letter", "SLP", "OT"] },
    { symbol: "H", type: "text", system: "Alphabet", label: "H", tags: ["letter", "SLP", "OT"] },
    { symbol: "I", type: "text", system: "Alphabet", label: "I", tags: ["letter", "SLP", "OT"] },
    { symbol: "J", type: "text", system: "Alphabet", label: "J", tags: ["letter", "SLP", "OT"] },
    { symbol: "K", type: "text", system: "Alphabet", label: "K", tags: ["letter", "SLP", "OT"] },
    { symbol: "L", type: "text", system: "Alphabet", label: "L", tags: ["letter", "SLP", "OT"] },
    { symbol: "M", type: "text", system: "Alphabet", label: "M", tags: ["letter", "SLP", "OT"] },
    { symbol: "N", type: "text", system: "Alphabet", label: "N", tags: ["letter", "SLP", "OT"] },
    { symbol: "O", type: "text", system: "Alphabet", label: "O", tags: ["letter", "SLP", "OT"] },
    { symbol: "P", type: "text", system: "Alphabet", label: "P", tags: ["letter", "SLP", "OT"] },
    { symbol: "Q", type: "text", system: "Alphabet", label: "Q", tags: ["letter", "SLP", "OT"] },
    { symbol: "R", type: "text", system: "Alphabet", label: "R", tags: ["letter", "SLP", "OT"] },
    { symbol: "S", type: "text", system: "Alphabet", label: "S", tags: ["letter", "SLP", "OT"] },
    { symbol: "T", type: "text", system: "Alphabet", label: "T", tags: ["letter", "SLP", "OT"] },
    { symbol: "U", type: "text", system: "Alphabet", label: "U", tags: ["letter", "SLP", "OT"] },
    { symbol: "V", type: "text", system: "Alphabet", label: "V", tags: ["letter", "SLP", "OT"] },
    { symbol: "W", type: "text", system: "Alphabet", label: "W", tags: ["letter", "SLP", "OT"] },
    { symbol: "X", type: "text", system: "Alphabet", label: "X", tags: ["letter", "SLP", "OT"] },
    { symbol: "Y", type: "text", system: "Alphabet", label: "Y", tags: ["letter", "SLP", "OT"] },
    { symbol: "Z", type: "text", system: "Alphabet", label: "Z", tags: ["letter", "SLP", "OT"] },
    {
        symbol: `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 100 100"><circle cx="50" cy="50" r="40" fill="red" stroke="black" stroke-width="3"/></svg>`,
        type: "svg",
        system: "shapes",
        label: "Circle",
        tags: ["shape", "OT"]
    },
    {
        symbol: `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 100 100"><rect x="20" y="20" width="60" height="60" fill="blue" stroke="black" stroke-width="3"/></svg>`,
        type: "svg",
        system: "shapes",
        label: "Square",
        tags: ["shape", "OT"]
    },
    {
        symbol: `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 100 100"><polygon points="50,10 90,90 10,90" fill="green" stroke="black" stroke-width="3"/></svg>`,
        type: "svg",
        system: "shapes",
        label: "Triangle",
        tags: ["shape", "OT"]
    },
    {
        symbol: `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 100 100"><ellipse cx="50" cy="50" rx="40" ry="25" fill="purple" stroke="black" stroke-width="3"/></svg>`,
        type: "svg",
        system: "shapes",
        label: "Oval",
        tags: ["shape", "OT"]
    },
    {
        symbol: `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 100 100"><polygon points="50,10 90,50 70,90 30,90 10,50" fill="cyan" stroke="black" stroke-width="3"/></svg>`,
        type: "svg",
        system: "shapes",
        label: "Pentagon",
        tags: ["shape", "OT"]
    },
    {
        symbol: `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 100 100"><polygon points="50,10 61,40 90,40 67,60 76,90 50,70 24,90 33,60 10,40 39,40" fill="yellow" stroke="black" stroke-width="3"/></svg>`,
        type: "svg",
        system: "shapes",
        label: "Star",
        tags: ["shape", "OT"]
    },
    {
        symbol: `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 100 100"><polygon points="25,10 75,10 90,50 75,90 25,90 10,50" fill="pink" stroke="black" stroke-width="3"/></svg>`,
        type: "svg",
        system: "shapes",
        label: "Hexagon",
        tags: ["shape", "OT"]
    },
    {
        symbol: `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 100 100"><line x1="10" y1="10" x2="90" y2="90" stroke="black" stroke-width="5"/><line x1="90" y1="10" x2="10" y2="90" stroke="black" stroke-width="5"/></svg>`,
        type: "svg",
        system: "shapes",
        label: "Cross",
        tags: ["shape", "OT", "symbol"]
    },
    { symbol: "😊", type: "emoji", system: "device", label: "Smiling Face", tags: ["emotion"] },
    { symbol: "🦉", type: "emoji", system: "device", label: "Owl", tags: ["nature"] },
    { symbol: "🪰", type: "emoji", system: "device", label: "Fly", tags: ["nature"] },
    { symbol: "🐝", type: "emoji", system: "device", label: "Bee", tags: ["nature"] },
    { symbol: "🐞", type: "emoji", system: "device", label: "Ladybug", tags: ["nature"] },
    { symbol: "🦓", type: "emoji", system: "device", label: "Zebra", tags: ["nature"] },
    { symbol: "🐙", type: "emoji", system: "device", label: "Octopus", tags: ["nature"] },
    { symbol: "🌙", type: "emoji", system: "device", label: "Moon", tags: ["nature"] },
    { symbol: "🦀", type: "emoji", system: "device", label: "Crab", tags: ["nature"] },
    { symbol: "🦞", type: "emoji", system: "device", label: "Lobster", tags: ["nature"] },
    { symbol: "😂", type: "emoji", system: "device", label: "Face with Tears of Joy", tags: ["emotion"] },
    { symbol: "❤️", type: "emoji", system: "device", label: "Red Heart", tags: ["emotion"] },
    { symbol: "😍", type: "emoji", system: "device", label: "Smiling Face with Heart-Eyes", tags: ["emotion"] },
    { symbol: "🤩", type: "emoji", system: "device", label: "Star-Struck", tags: ["emotion"] },
    { symbol: "🙏", type: "emoji", system: "device", label: "Folded Hands", tags: ["symbols"] },
    { symbol: "🔥", type: "emoji", system: "device", label: "Fire", tags: ["nature"] },
    { symbol: "🎂", type: "emoji", system: "device", label: "Birthday Cake", tags: ["food"] },
    { symbol: "✨", type: "emoji", system: "device", label: "Sparkles", tags: ["symbols"] },
    { symbol: "./images/more.png", type: "image", system: "Proloquo2Go", label: "More", tags: ["symbols", "OT", "SLP"] },
    { symbol: "./images/all-done.png", type: "image", system: "Proloquo2Go", label: "All Done", tags: ["symbols", "OT", "SLP"] }
];
